namespace: kube-system

updateStrategy:
  type: RollingUpdate

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists

imagePullSecrets: []
image:
  repository: ghcr.io/h-s-c/edge-device-plugin
  pullPolicy: Always
  # @default -- chart.appVersion
  tag: latest

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
